spring:
  application:
    name: travel-commerce
  datasource:
    url: jdbc:mysql://localhost:3306/travel_commerce
    username: root
    password: ekdlth2233
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration: {}

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug

